os:
- linux
language: node_js
notifications:
  email:
    on_success: never
    on_failure: never
sudo: true
branches:
  only:
  - master
  - develop
node_js:
- '7'
- '6'
cache:
  apt: true
  directories:
  - node_modules
before_install: npm install -g grunt-cli
script: npm run-script test-travis
after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  echo "Building docs for GH pages..." &&
  grunt docs &&
  sudo pip install ghp-import &&
  ghp-import -n doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages &&
  echo "Finished building docs for GH pages."
env:
  global:
  - CXX=g++-4.8
  - secure: S2ogBC/CkkTZ3bvYxRPq1cNdZfg045OERatJDSW4U6yUoHnRxU9Mau5meeCovRvquGrH37mWahO/h3++iDyn9Mefb8oUDXCAlCjyzkks8wpF4dTDPo6J2AcCNHspK8X4jFVa0azIoF1k44gbqX5FG42F5meeL70FEPurO4mHT19lFHzwp/FdJ8D/uLc3nnQZ0ifjlltv16Olbth4rw3lHvxK5V2Q8pU8fzZfAgfI5zfjfwVt94G1uhsnc9BcojENyLfjmpfXYicTnA48PbpYtzIe8O206xuTgdxKTy89GrL1zVUw47Tor1Lb0wae1JQWYy+ZWipE1/PKoTqoJ9vO5RxwuG/TngkLLGSRsiMuQZRa7kPxfjKux5HCIeRXwdVa99y5XBVdUkFEHWJ9Bc762cIuqQE/7yJz29tyLakUrj/Ok7ELu+kgX6Nh9ukbGOVhbyXRIj60psOSrCqBdLH/unwweJvk1pqObPQqBfy+ffym0mHtdfBt8eUbRNQ1ahzoJ94RW8VUmM3c1YUvZZB2RiMvMKgsIo49uePl4fesfs/XadAEv3To5P+C1IooYVmLjz1eKp1PuVGb4S06WXtAbjnY4AeH/brGlR03oAkRCOSNB6/TwHTBdRAPgwQjG7zhebujbtTJDgXnQ2cOHSLaTHChV/BjB+hib7vEE9cmke8=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
